SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `tb_customer_agent_run` (
  `run_id` varchar(32) NOT NULL COMMENT 'Agent运行ID',
  `request_id` varchar(64) NOT NULL COMMENT '跨服务幂等请求ID',
  `user_message_id` bigint(20) NOT NULL COMMENT '触发运行的用户消息ID',
  `im_chat_id` bigint(20) NOT NULL COMMENT '长会话ID',
  `chat_id` bigint(20) NOT NULL COMMENT '短会话ID/LangGraph thread ID',
  `user_id` bigint(20) UNSIGNED NOT NULL COMMENT '所属用户ID',
  `status` varchar(24) NOT NULL COMMENT 'PENDING/RUNNING/AWAITING_CONFIRMATION/RESUMING/SUCCEEDED/FAILED_*',
  `retryable` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否允许安全重试',
  `attempt_count` int(11) NOT NULL DEFAULT 0 COMMENT '执行尝试次数',
  `trace_id` varchar(64) DEFAULT NULL COMMENT 'Agent链路追踪ID',
  `error_code` varchar(64) DEFAULT NULL COMMENT '最近错误码',
  `graph_version` varchar(16) NOT NULL DEFAULT 'v4' COMMENT 'LangGraph版本',
  `entry_agent` varchar(32) DEFAULT NULL COMMENT '入口Agent',
  `final_agent` varchar(32) DEFAULT NULL COMMENT '最终回复Agent',
  `route_history` longtext COMMENT '路由历史JSON',
  `handoff_count` int(11) NOT NULL DEFAULT 0 COMMENT '顺序Handoff次数',
  `model_call_count` int(11) NOT NULL DEFAULT 0 COMMENT '模型调用次数',
  `tool_call_count` int(11) NOT NULL DEFAULT 0 COMMENT '工具调用次数',
  `prompt_tokens` int(11) NOT NULL DEFAULT 0 COMMENT '输入Token数',
  `completion_tokens` int(11) NOT NULL DEFAULT 0 COMMENT '输出Token数',
  `execution_mode` varchar(16) NOT NULL DEFAULT 'SIMPLE' COMMENT 'SIMPLE或COMPLEX',
  `plan_id` varchar(64) DEFAULT NULL COMMENT 'Supervisor计划ID',
  `supervisor_iterations` int(11) NOT NULL DEFAULT 0 COMMENT 'Supervisor规划迭代次数',
  `parallel_task_count` int(11) NOT NULL DEFAULT 0 COMMENT '并行编排任务数',
  `task_outcomes` longtext COMMENT '领域任务执行结果JSON',
  `orchestrator` varchar(32) NOT NULL DEFAULT 'router' COMMENT 'router或supervisor',
  `resolution_type` varchar(32) DEFAULT NULL,
  `action_request_id` varchar(32) DEFAULT NULL,
  `action_type` varchar(32) DEFAULT NULL,
  `action_status` varchar(32) DEFAULT NULL,
  `interrupt_reason` varchar(64) DEFAULT NULL,
  `resume_count` int(11) NOT NULL DEFAULT 0,
  `handoff_reason_code` varchar(64) DEFAULT NULL,
  `started_time` datetime DEFAULT NULL COMMENT '最近开始时间',
  `finished_time` datetime DEFAULT NULL COMMENT '完成时间',
  `update_time` datetime NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`run_id`) USING BTREE,
  UNIQUE KEY `uk_agent_run_request` (`request_id`) USING BTREE,
  UNIQUE KEY `uk_agent_run_user_message` (`user_message_id`) USING BTREE,
  KEY `idx_agent_run_chat_status` (`chat_id`, `status`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='客服Agent运行审计';
