from opentelemetry import metrics


meter = metrics.get_meter("smarthub.agent_service")
routes = meter.create_counter("smarthub.agent.routes")
agent_activations = meter.create_counter("smarthub.agent.activations")
low_confidence_routes = meter.create_counter("smarthub.agent.router.low_confidence")
keyword_route_hits = meter.create_counter("smarthub.agent.router.rule_hits")
keyword_route_fallbacks = meter.create_counter("smarthub.agent.router.llm_fallbacks")
keyword_route_blocks = meter.create_counter("smarthub.agent.router.rule_blocks")
specialist_calls = meter.create_counter("smarthub.agent.specialist.calls")
specialist_failures = meter.create_counter("smarthub.agent.specialist.failures")
specialist_cache_hits = meter.create_counter("smarthub.agent.specialist.cache_hits")
faq_requests = meter.create_counter("smarthub.agent.faq.requests")
faq_retries = meter.create_counter("smarthub.agent.faq.retries")
faq_grounded_answers = meter.create_counter("smarthub.agent.faq.grounded_answers")
faq_no_evidence = meter.create_counter("smarthub.agent.faq.no_evidence")
faq_out_of_scope = meter.create_counter("smarthub.agent.faq.out_of_scope")
faq_failures = meter.create_counter("smarthub.agent.faq.failures")
faq_agent_results = meter.create_counter("smarthub.agent.faq.agent_results")
handoffs = meter.create_counter("smarthub.agent.handoffs")
handoff_blocks = meter.create_counter("smarthub.agent.handoff.blocks")
supervisor_plans = meter.create_counter("smarthub.agent.supervisor.plans")
supervisor_reviews = meter.create_counter("smarthub.agent.supervisor.reviews")
supervisor_replans = meter.create_counter("smarthub.agent.supervisor.replans")
execution_waves = meter.create_counter("smarthub.agent.supervisor.waves")
parallel_tasks = meter.create_counter("smarthub.agent.supervisor.parallel_tasks")
partial_failures = meter.create_counter("smarthub.agent.supervisor.partial_failures")
tool_calls = meter.create_counter("smarthub.agent.tool.calls")
tool_failures = meter.create_counter("smarthub.agent.tool.failures")
model_calls = meter.create_counter("smarthub.agent.model.calls")
tokens = meter.create_counter("smarthub.agent.tokens")
run_latency = meter.create_histogram("smarthub.agent.run.duration", unit="s")
errors = meter.create_counter("smarthub.agent.errors")
action_proposals = meter.create_counter("smarthub.agent.action.proposals")
confirmation_interrupts = meter.create_counter("smarthub.agent.action.interrupts")
action_resumes = meter.create_counter("smarthub.agent.action.resumes")
human_handoff_proposals = meter.create_counter("smarthub.agent.human_handoff.proposals")
